// This file is auto-generated by scripts/generate-docs-manifest.ts
// Do not edit manually.

export const demoImports: Record<string, () => Promise<Record<string, unknown>>> = {
  "contact-01": () => import("@/components/blocks/contact-01/contact-01.demo"),
  "faq-01": () => import("@/components/blocks/faq-01/faq-01.demo"),
  "hero-01": () => import("@/components/blocks/hero-01/hero-01.demo"),
  "pricing-01": () => import("@/components/blocks/pricing-01/pricing-01.demo"),
  "accordion": () => import("@/components/ui/Accordion/accordion.demo"),
  "badge": () => import("@/components/ui/Badge/badge.demo"),
  "button": () => import("@/components/ui/Button/button.demo"),
  "card": () => import("@/components/ui/Card/card.demo"),
  "dialog": () => import("@/components/ui/Dialog/dialog.demo"),
  "input": () => import("@/components/ui/Input/input.demo"),
  "select": () => import("@/components/ui/Select/select.demo"),
  "switch": () => import("@/components/ui/Switch/switch.demo"),
  "table": () => import("@/components/ui/Table/table.demo"),
  "tabs": () => import("@/components/ui/Tabs/tabs.demo"),
};
