/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeBuilderRouteImport } from './routes/theme-builder'
import { Route as OgRouteImport } from './routes/og'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BlocksRouteImport } from './routes/blocks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as BlocksIndexRouteImport } from './routes/blocks/index'
import { Route as DocsThemingRouteImport } from './routes/docs/theming'
import { Route as DocsStylingRouteImport } from './routes/docs/styling'
import { Route as DocsPrimitivesRouteImport } from './routes/docs/primitives'
import { Route as DocsLimitationsRouteImport } from './routes/docs/limitations'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as BlocksMarketingRouteImport } from './routes/blocks/marketing'
import { Route as BlocksDashboardRouteImport } from './routes/blocks/dashboard'
import { Route as BlocksAuthenticationRouteImport } from './routes/blocks/authentication'
import { Route as BlocksApplicationStatesRouteImport } from './routes/blocks/application-states'
import { Route as DocsComponentsDataTableRouteImport } from './routes/docs/components/data-table'
import { Route as DocsComponentsComponentRouteImport } from './routes/docs/components/$component'

const ThemeBuilderRoute = ThemeBuilderRouteImport.update({
  id: '/theme-builder',
  path: '/theme-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRoute = BlocksRouteImport.update({
  id: '/blocks',
  path: '/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlocksRoute,
} as any)
const DocsThemingRoute = DocsThemingRouteImport.update({
  id: '/theming',
  path: '/theming',
  getParentRoute: () => DocsRoute,
} as any)
const DocsStylingRoute = DocsStylingRouteImport.update({
  id: '/styling',
  path: '/styling',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPrimitivesRoute = DocsPrimitivesRouteImport.update({
  id: '/primitives',
  path: '/primitives',
  getParentRoute: () => DocsRoute,
} as any)
const DocsLimitationsRoute = DocsLimitationsRouteImport.update({
  id: '/limitations',
  path: '/limitations',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const BlocksMarketingRoute = BlocksMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => BlocksRoute,
} as any)
const BlocksDashboardRoute = BlocksDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BlocksRoute,
} as any)
const BlocksAuthenticationRoute = BlocksAuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => BlocksRoute,
} as any)
const BlocksApplicationStatesRoute = BlocksApplicationStatesRouteImport.update({
  id: '/application-states',
  path: '/application-states',
  getParentRoute: () => BlocksRoute,
} as any)
const DocsComponentsDataTableRoute = DocsComponentsDataTableRouteImport.update({
  id: '/components/data-table',
  path: '/components/data-table',
  getParentRoute: () => DocsRoute,
} as any)
const DocsComponentsComponentRoute = DocsComponentsComponentRouteImport.update({
  id: '/components/$component',
  path: '/components/$component',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/og': typeof OgRoute
  '/theme-builder': typeof ThemeBuilderRoute
  '/blocks/application-states': typeof BlocksApplicationStatesRoute
  '/blocks/authentication': typeof BlocksAuthenticationRoute
  '/blocks/dashboard': typeof BlocksDashboardRoute
  '/blocks/marketing': typeof BlocksMarketingRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/limitations': typeof DocsLimitationsRoute
  '/docs/primitives': typeof DocsPrimitivesRoute
  '/docs/styling': typeof DocsStylingRoute
  '/docs/theming': typeof DocsThemingRoute
  '/blocks/': typeof BlocksIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/components/$component': typeof DocsComponentsComponentRoute
  '/docs/components/data-table': typeof DocsComponentsDataTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/og': typeof OgRoute
  '/theme-builder': typeof ThemeBuilderRoute
  '/blocks/application-states': typeof BlocksApplicationStatesRoute
  '/blocks/authentication': typeof BlocksAuthenticationRoute
  '/blocks/dashboard': typeof BlocksDashboardRoute
  '/blocks/marketing': typeof BlocksMarketingRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/limitations': typeof DocsLimitationsRoute
  '/docs/primitives': typeof DocsPrimitivesRoute
  '/docs/styling': typeof DocsStylingRoute
  '/docs/theming': typeof DocsThemingRoute
  '/blocks': typeof BlocksIndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/components/$component': typeof DocsComponentsComponentRoute
  '/docs/components/data-table': typeof DocsComponentsDataTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks': typeof BlocksRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/og': typeof OgRoute
  '/theme-builder': typeof ThemeBuilderRoute
  '/blocks/application-states': typeof BlocksApplicationStatesRoute
  '/blocks/authentication': typeof BlocksAuthenticationRoute
  '/blocks/dashboard': typeof BlocksDashboardRoute
  '/blocks/marketing': typeof BlocksMarketingRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/limitations': typeof DocsLimitationsRoute
  '/docs/primitives': typeof DocsPrimitivesRoute
  '/docs/styling': typeof DocsStylingRoute
  '/docs/theming': typeof DocsThemingRoute
  '/blocks/': typeof BlocksIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/components/$component': typeof DocsComponentsComponentRoute
  '/docs/components/data-table': typeof DocsComponentsDataTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks'
    | '/docs'
    | '/og'
    | '/theme-builder'
    | '/blocks/application-states'
    | '/blocks/authentication'
    | '/blocks/dashboard'
    | '/blocks/marketing'
    | '/docs/installation'
    | '/docs/limitations'
    | '/docs/primitives'
    | '/docs/styling'
    | '/docs/theming'
    | '/blocks/'
    | '/docs/'
    | '/docs/components/$component'
    | '/docs/components/data-table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/og'
    | '/theme-builder'
    | '/blocks/application-states'
    | '/blocks/authentication'
    | '/blocks/dashboard'
    | '/blocks/marketing'
    | '/docs/installation'
    | '/docs/limitations'
    | '/docs/primitives'
    | '/docs/styling'
    | '/docs/theming'
    | '/blocks'
    | '/docs'
    | '/docs/components/$component'
    | '/docs/components/data-table'
  id:
    | '__root__'
    | '/'
    | '/blocks'
    | '/docs'
    | '/og'
    | '/theme-builder'
    | '/blocks/application-states'
    | '/blocks/authentication'
    | '/blocks/dashboard'
    | '/blocks/marketing'
    | '/docs/installation'
    | '/docs/limitations'
    | '/docs/primitives'
    | '/docs/styling'
    | '/docs/theming'
    | '/blocks/'
    | '/docs/'
    | '/docs/components/$component'
    | '/docs/components/data-table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksRoute: typeof BlocksRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  OgRoute: typeof OgRoute
  ThemeBuilderRoute: typeof ThemeBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme-builder': {
      id: '/theme-builder'
      path: '/theme-builder'
      fullPath: '/theme-builder'
      preLoaderRoute: typeof ThemeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks': {
      id: '/blocks'
      path: '/blocks'
      fullPath: '/blocks'
      preLoaderRoute: typeof BlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/'
      fullPath: '/blocks/'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof BlocksRoute
    }
    '/docs/theming': {
      id: '/docs/theming'
      path: '/theming'
      fullPath: '/docs/theming'
      preLoaderRoute: typeof DocsThemingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/styling': {
      id: '/docs/styling'
      path: '/styling'
      fullPath: '/docs/styling'
      preLoaderRoute: typeof DocsStylingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/primitives': {
      id: '/docs/primitives'
      path: '/primitives'
      fullPath: '/docs/primitives'
      preLoaderRoute: typeof DocsPrimitivesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/limitations': {
      id: '/docs/limitations'
      path: '/limitations'
      fullPath: '/docs/limitations'
      preLoaderRoute: typeof DocsLimitationsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/blocks/marketing': {
      id: '/blocks/marketing'
      path: '/marketing'
      fullPath: '/blocks/marketing'
      preLoaderRoute: typeof BlocksMarketingRouteImport
      parentRoute: typeof BlocksRoute
    }
    '/blocks/dashboard': {
      id: '/blocks/dashboard'
      path: '/dashboard'
      fullPath: '/blocks/dashboard'
      preLoaderRoute: typeof BlocksDashboardRouteImport
      parentRoute: typeof BlocksRoute
    }
    '/blocks/authentication': {
      id: '/blocks/authentication'
      path: '/authentication'
      fullPath: '/blocks/authentication'
      preLoaderRoute: typeof BlocksAuthenticationRouteImport
      parentRoute: typeof BlocksRoute
    }
    '/blocks/application-states': {
      id: '/blocks/application-states'
      path: '/application-states'
      fullPath: '/blocks/application-states'
      preLoaderRoute: typeof BlocksApplicationStatesRouteImport
      parentRoute: typeof BlocksRoute
    }
    '/docs/components/data-table': {
      id: '/docs/components/data-table'
      path: '/components/data-table'
      fullPath: '/docs/components/data-table'
      preLoaderRoute: typeof DocsComponentsDataTableRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/components/$component': {
      id: '/docs/components/$component'
      path: '/components/$component'
      fullPath: '/docs/components/$component'
      preLoaderRoute: typeof DocsComponentsComponentRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface BlocksRouteChildren {
  BlocksApplicationStatesRoute: typeof BlocksApplicationStatesRoute
  BlocksAuthenticationRoute: typeof BlocksAuthenticationRoute
  BlocksDashboardRoute: typeof BlocksDashboardRoute
  BlocksMarketingRoute: typeof BlocksMarketingRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
}

const BlocksRouteChildren: BlocksRouteChildren = {
  BlocksApplicationStatesRoute: BlocksApplicationStatesRoute,
  BlocksAuthenticationRoute: BlocksAuthenticationRoute,
  BlocksDashboardRoute: BlocksDashboardRoute,
  BlocksMarketingRoute: BlocksMarketingRoute,
  BlocksIndexRoute: BlocksIndexRoute,
}

const BlocksRouteWithChildren =
  BlocksRoute._addFileChildren(BlocksRouteChildren)

interface DocsRouteChildren {
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsLimitationsRoute: typeof DocsLimitationsRoute
  DocsPrimitivesRoute: typeof DocsPrimitivesRoute
  DocsStylingRoute: typeof DocsStylingRoute
  DocsThemingRoute: typeof DocsThemingRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsComponentsComponentRoute: typeof DocsComponentsComponentRoute
  DocsComponentsDataTableRoute: typeof DocsComponentsDataTableRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsInstallationRoute: DocsInstallationRoute,
  DocsLimitationsRoute: DocsLimitationsRoute,
  DocsPrimitivesRoute: DocsPrimitivesRoute,
  DocsStylingRoute: DocsStylingRoute,
  DocsThemingRoute: DocsThemingRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsComponentsComponentRoute: DocsComponentsComponentRoute,
  DocsComponentsDataTableRoute: DocsComponentsDataTableRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksRoute: BlocksRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  OgRoute: OgRoute,
  ThemeBuilderRoute: ThemeBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
